#define WIN32_LEAN_AND_MEAN
#include <winsock2.h>
#include <windows.h>
#include <winhttp.h>
#include <shellapi.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define CHUNK 16384
#define MAX_HEADER 65536

typedef struct { SOCKET client; char root[MAX_PATH*4]; } CLIENT_JOB;
static CRITICAL_SECTION history_lock;

static int send_all(SOCKET s,const char*b,int n){int p=0;while(p<n){int k=send(s,b+p,n-p,0);if(k<=0)return 0;p+=k;}return 1;}
static const char*mime(const char*p){const char*e=strrchr(p,'.');if(!e)return"application/octet-stream";if(!_stricmp(e,".html"))return"text/html; charset=utf-8";if(!_stricmp(e,".js"))return"application/javascript; charset=utf-8";if(!_stricmp(e,".json"))return"application/json; charset=utf-8";if(!_stricmp(e,".css"))return"text/css; charset=utf-8";if(!_stricmp(e,".png"))return"image/png";if(!_stricmp(e,".jpg")||!_stricmp(e,".jpeg"))return"image/jpeg";if(!_stricmp(e,".webp"))return"image/webp";return"application/octet-stream";}
static void text_response(SOCKET c,int code,const char*reason,const char*body){char h[1024];int z=(int)strlen(body),n=snprintf(h,sizeof(h),"HTTP/1.1 %d %s\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: %d\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n",code,reason,z);send_all(c,h,n);send_all(c,body,z);}
static int header_value(const char*headers,const char*name,char*out,size_t cap){size_t nl=strlen(name);const char*p=headers;while((p=strstr(p,"\r\n"))){p+=2;if(!_strnicmp(p,name,nl)&&p[nl]==':'){p+=nl+1;while(*p==' '||*p=='\t')p++;const char*e=strstr(p,"\r\n");if(!e)return 0;size_t n=(size_t)(e-p);if(n>=cap)n=cap-1;memcpy(out,p,n);out[n]=0;return 1;}}return 0;}
static wchar_t*widen(const char*s){int n=MultiByteToWideChar(CP_UTF8,0,s,-1,NULL,0);wchar_t*w=(wchar_t*)calloc(n,sizeof(wchar_t));if(w)MultiByteToWideChar(CP_UTF8,0,s,-1,w,n);return w;}

static int safe_component(const char*s){if(!s||!*s||!strcmp(s,".")||!strcmp(s,".."))return 0;for(const char*p=s;*p;p++)if(!((*p>='a'&&*p<='z')||(*p>='A'&&*p<='Z')||(*p>='0'&&*p<='9')||*p=='-'||*p=='_'))return 0;return 1;}
static void output_root(const char*root,char*out,size_t cap){snprintf(out,cap,"%s\\output",root);CreateDirectoryA(out,NULL);}
static int write_file(const char*path,const void*data,size_t len){FILE*f=fopen(path,"wb");if(!f)return 0;size_t n=fwrite(data,1,len,f);fclose(f);return n==len;}
static int read_file_response(SOCKET c,const char*method,const char*path){FILE*f=fopen(path,"rb");if(!f){text_response(c,404,"Not Found","Not Found");return 0;}_fseeki64(f,0,SEEK_END);__int64 sz=_ftelli64(f);_fseeki64(f,0,SEEK_SET);char h[1024];int hn=snprintf(h,sizeof(h),"HTTP/1.1 200 OK\r\nContent-Type: %s\r\nContent-Length: %lld\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n",mime(path),(long long)sz);send_all(c,h,hn);if(_stricmp(method,"HEAD")){char b[CHUNK];int k;while((k=(int)fread(b,1,sizeof(b),f))>0)if(!send_all(c,b,k))break;}fclose(f);return 1;}
static int query_value(const char*target,const char*name,char*out,size_t cap){const char*q=strchr(target,'?');if(!q)return 0;q++;size_t nl=strlen(name);while(*q){const char*e=strchr(q,'&');if(!e)e=q+strlen(q);if((size_t)(e-q)>nl&&strncmp(q,name,nl)==0&&q[nl]=='='){size_t n=(size_t)(e-q)-nl-1;if(!n||n>=cap)return 0;memcpy(out,q+nl+1,n);out[n]=0;return 1;}if(!*e)break;q=e+1;}return 0;}
static void history_paths(const char*root,const char*project,char*dir,size_t dcap){char out[MAX_PATH*4];output_root(root,out,sizeof(out));snprintf(dir,dcap,"%s\\%s",out,project);CreateDirectoryA(dir,NULL);}
static void refresh_records_index(const char*dir){char pattern[MAX_PATH*4],indexPath[MAX_PATH*4];snprintf(pattern,sizeof(pattern),"%s\\record-*.json",dir);snprintf(indexPath,sizeof(indexPath),"%s\\records.json",dir);HANDLE h;WIN32_FIND_DATAA fd;h=FindFirstFileA(pattern,&fd);if(h==INVALID_HANDLE_VALUE){write_file(indexPath,"[]",2);return;}size_t cap=65536,len=0;char*all=(char*)malloc(cap);if(!all){FindClose(h);return;}all[len++]='[';int first=1;do{char path[MAX_PATH*4];snprintf(path,sizeof(path),"%s\\%s",dir,fd.cFileName);FILE*f=fopen(path,"rb");if(!f)continue;_fseeki64(f,0,SEEK_END);long long sz=_ftelli64(f);_fseeki64(f,0,SEEK_SET);if(sz<0||sz>2000000){fclose(f);continue;}if(len+(size_t)sz+3>cap){while(len+(size_t)sz+3>cap)cap*=2;char*next=(char*)realloc(all,cap);if(!next){fclose(f);free(all);FindClose(h);return;}all=next;}if(!first)all[len++]=',';first=0;len+=fread(all+len,1,(size_t)sz,f);fclose(f);}while(FindNextFileA(h,&fd));FindClose(h);all[len++]=']';write_file(indexPath,all,len);free(all);}
static void remove_tree(const char*dir){char pattern[MAX_PATH*4];snprintf(pattern,sizeof(pattern),"%s\\*",dir);WIN32_FIND_DATAA fd;HANDLE h=FindFirstFileA(pattern,&fd);if(h!=INVALID_HANDLE_VALUE){do{if(!strcmp(fd.cFileName,".")||!strcmp(fd.cFileName,".."))continue;char path[MAX_PATH*4];snprintf(path,sizeof(path),"%s\\%s",dir,fd.cFileName);if(fd.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY)remove_tree(path);else DeleteFileA(path);}while(FindNextFileA(h,&fd));FindClose(h);}RemoveDirectoryA(dir);}

static void history_record(SOCKET c,const char*root,const char*headers,unsigned char*body,DWORD total){char project[256],record[256],mlbuf[64];if(!header_value(headers,"X-History-Project",project,sizeof(project))||!header_value(headers,"X-History-Record",record,sizeof(record))||!header_value(headers,"X-History-Meta-Length",mlbuf,sizeof(mlbuf))||!safe_component(project)||!safe_component(record)){text_response(c,400,"Bad Request","Invalid history record headers");return;}DWORD metaLen=(DWORD)strtoul(mlbuf,NULL,10);if(!metaLen||metaLen>=total){text_response(c,400,"Bad Request","Invalid history metadata");return;}char dir[MAX_PATH*4],path[MAX_PATH*4];EnterCriticalSection(&history_lock);history_paths(root,project,dir,sizeof(dir));snprintf(path,sizeof(path),"%s\\record-%s.json",dir,record);if(!write_file(path,body,metaLen)){LeaveCriticalSection(&history_lock);text_response(c,500,"Error","Unable to save history metadata");return;}snprintf(path,sizeof(path),"%s\\image-%s.png",dir,record);if(!write_file(path,body+metaLen,total-metaLen)){LeaveCriticalSection(&history_lock);text_response(c,500,"Error","Unable to save history image");return;}refresh_records_index(dir);LeaveCriticalSection(&history_lock);text_response(c,200,"OK","{\"ok\":true}");}
static void history_projects(SOCKET c,const char*root,const char*method,unsigned char*body,DWORD total){char out[MAX_PATH*4],path[MAX_PATH*4];output_root(root,out,sizeof(out));snprintf(path,sizeof(path),"%s\\projects.json",out);if(!_stricmp(method,"POST")){EnterCriticalSection(&history_lock);int ok=total&&write_file(path,body,total);LeaveCriticalSection(&history_lock);if(!ok){text_response(c,500,"Error","Unable to save project index");return;}text_response(c,200,"OK","{\"ok\":true}");return;}if(!_stricmp(method,"GET")||!_stricmp(method,"HEAD")){FILE*f=fopen(path,"rb");if(!f){const char*empty="{\"version\":1,\"projects\":[]}";write_file(path,empty,strlen(empty));}else fclose(f);read_file_response(c,method,path);return;}text_response(c,405,"Method Not Allowed","Method Not Allowed");}
static void history_delete_project(SOCKET c,const char*root,const char*headers){char project[256];if(!header_value(headers,"X-History-Project",project,sizeof(project))||!safe_component(project)){text_response(c,400,"Bad Request","Invalid history project");return;}char dir[MAX_PATH*4];EnterCriticalSection(&history_lock);history_paths(root,project,dir,sizeof(dir));remove_tree(dir);LeaveCriticalSection(&history_lock);text_response(c,200,"OK","{\"ok\":true}");}
static void history_delete_record(SOCKET c,const char*root,const char*headers){char project[256],record[256];if(!header_value(headers,"X-History-Project",project,sizeof(project))||!header_value(headers,"X-History-Record",record,sizeof(record))||!safe_component(project)||!safe_component(record)){text_response(c,400,"Bad Request","Invalid history record");return;}char dir[MAX_PATH*4],path[MAX_PATH*4];EnterCriticalSection(&history_lock);history_paths(root,project,dir,sizeof(dir));snprintf(path,sizeof(path),"%s\\record-%s.json",dir,record);DeleteFileA(path);snprintf(path,sizeof(path),"%s\\image-%s.png",dir,record);DeleteFileA(path);refresh_records_index(dir);LeaveCriticalSection(&history_lock);text_response(c,200,"OK","{\"ok\":true}");}
static int history_request(SOCKET c,const char*root,const char*method,char*target,const char*headers,unsigned char*body,DWORD total){char path[4096];strncpy(path,target,sizeof(path)-1);path[sizeof(path)-1]=0;char*q=strchr(path,'?');if(q)*q=0;if(!strncmp(path,"/history/projects",17)&&!path[17]){history_projects(c,root,method,body,total);return 1;}if(!strcmp(path,"/history/record")&&!_stricmp(method,"POST")){history_record(c,root,headers,body,total);return 1;}if(!strcmp(path,"/history/record/delete")&&!_stricmp(method,"POST")){history_delete_record(c,root,headers);return 1;}if(!strcmp(path,"/history/project/delete")&&!_stricmp(method,"POST")){history_delete_project(c,root,headers);return 1;}if((!strcmp(path,"/history/records")||!strcmp(path,"/history/image"))&&!_stricmp(method,"GET")){char project[256],record[256],dir[MAX_PATH*4],file[MAX_PATH*4];if(!query_value(target,"project",project,sizeof(project))||!safe_component(project)){text_response(c,400,"Bad Request","Invalid history project");return 1;}history_paths(root,project,dir,sizeof(dir));if(!strcmp(path,"/history/records")){snprintf(file,sizeof(file),"%s\\records.json",dir);FILE*f=fopen(file,"rb");if(f){fclose(f);read_file_response(c,method,file);}else text_response(c,200,"OK","[]");}else{if(!query_value(target,"record",record,sizeof(record))||!safe_component(record)){text_response(c,400,"Bad Request","Invalid history record");return 1;}snprintf(file,sizeof(file),"%s\\image-%s.png",dir,record);read_file_response(c,method,file);}return 1;}if(!strcmp(path,"/history/info")&&(!_stricmp(method,"GET")||!_stricmp(method,"HEAD"))){text_response(c,200,"OK","{\"mode\":\"default\",\"folder\":\"output\"}");return 1;}return 0;}

static void proxy_request(SOCKET c,const char*method,char*headers,unsigned char*body,DWORD body_len){
 char target[4096],auth[8192],ctype[1024]; if(!header_value(headers,"X-Target-URL",target,sizeof(target))||_strnicmp(target,"https://",8)){text_response(c,400,"Bad Request","Missing or invalid X-Target-URL");return;}
 int has_auth=header_value(headers,"Authorization",auth,sizeof(auth)); int has_ctype=header_value(headers,"Content-Type",ctype,sizeof(ctype));
 wchar_t*wurl=widen(target); URL_COMPONENTS u;memset(&u,0,sizeof(u));u.dwStructSize=sizeof(u);u.dwSchemeLength=(DWORD)-1;u.dwHostNameLength=(DWORD)-1;u.dwUrlPathLength=(DWORD)-1;u.dwExtraInfoLength=(DWORD)-1;
 if(!wurl||!WinHttpCrackUrl(wurl,0,0,&u)){free(wurl);text_response(c,502,"Bad Gateway","Invalid target URL");return;}
 wchar_t host[512],path[4096];DWORD hn=u.dwHostNameLength;if(hn>511)hn=511;wcsncpy(host,u.lpszHostName,hn);host[hn]=0;DWORD pn=0;if(u.dwUrlPathLength){wcsncpy(path,u.lpszUrlPath,u.dwUrlPathLength);pn=u.dwUrlPathLength;}if(u.dwExtraInfoLength){wcsncpy(path+pn,u.lpszExtraInfo,u.dwExtraInfoLength);pn+=u.dwExtraInfoLength;}path[pn]=0;
 HINTERNET ses=WinHttpOpen(L"GPTImagePortable/4.0",WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,WINHTTP_NO_PROXY_NAME,WINHTTP_NO_PROXY_BYPASS,0);HINTERNET con=NULL,req=NULL;DWORD status=502;wchar_t ct[512]=L"application/octet-stream";DWORD ctl=sizeof(ct);
 /* WinHTTP defaults can time out long image edits at about 30 seconds. Keep connect bounded, but allow a 20-minute response. */
 if(ses)WinHttpSetTimeouts(ses,30000,30000,30000,1200000);
 /* The gateway intermittently returns malformed/empty replies to long multipart edits over negotiated HTTP/2 (WinHTTP 12152). Force HTTP/1.1 for compatibility. */
 HTTP_VERSION_INFO http11={1,1};
 if(ses)WinHttpSetOption(ses,WINHTTP_OPTION_HTTP_VERSION,&http11,sizeof(http11));
 if(ses)con=WinHttpConnect(ses,host,u.nPort,0);wchar_t*wm=widen(method);if(con)req=WinHttpOpenRequest(con,wm,path,NULL,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,WINHTTP_FLAG_SECURE);free(wm);
 wchar_t extra[8192];extra[0]=0;if(has_auth){wchar_t*wa=widen(auth);_snwprintf(extra,8191,L"Authorization: %ls\r\n",wa);free(wa);}if(has_ctype){wchar_t*wc=widen(ctype);size_t used=wcslen(extra);_snwprintf(extra+used,8191-used,L"Content-Type: %ls\r\n",wc);free(wc);}
 BOOL ok=req&&WinHttpSendRequest(req,extra[0]?extra:WINHTTP_NO_ADDITIONAL_HEADERS,(DWORD)-1L,body_len?body:WINHTTP_NO_REQUEST_DATA,body_len,body_len,0)&&WinHttpReceiveResponse(req,NULL);
 if(ok){DWORD sl=sizeof(status);WinHttpQueryHeaders(req,WINHTTP_QUERY_STATUS_CODE|WINHTTP_QUERY_FLAG_NUMBER,NULL,&status,&sl,NULL);WinHttpQueryHeaders(req,WINHTTP_QUERY_CONTENT_TYPE,NULL,ct,&ctl,NULL);}
 if(!ok){DWORD err=GetLastError();char msg[256];snprintf(msg,sizeof(msg),"Upstream request failed (WinHTTP error %lu)",(unsigned long)err);text_response(c,502,"Bad Gateway",msg);}
 else{char ctu[1024];WideCharToMultiByte(CP_UTF8,0,ct,-1,ctu,sizeof(ctu),NULL,NULL);char h[2048];int n=snprintf(h,sizeof(h),"HTTP/1.1 %lu Upstream\r\nContent-Type: %s\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n",(unsigned long)status,ctu);send_all(c,h,n);unsigned char b[CHUNK];DWORD got=0;while(WinHttpReadData(req,b,sizeof(b),&got)&&got){if(!send_all(c,(char*)b,(int)got))break;}}
 if(req)WinHttpCloseHandle(req);if(con)WinHttpCloseHandle(con);if(ses)WinHttpCloseHandle(ses);free(wurl);
}

static void handle(SOCKET c,const char*root){
 unsigned char*req=(unsigned char*)malloc(MAX_HEADER);int used=0,k;char*end=NULL;while(used<MAX_HEADER-1){k=recv(c,(char*)req+used,MAX_HEADER-1-used,0);if(k<=0){free(req);return;}used+=k;req[used]=0;end=strstr((char*)req,"\r\n\r\n");if(end)break;}if(!end){free(req);text_response(c,431,"Too Large","Headers too large");return;}
 char method[16],target[4096],ver[32];if(sscanf((char*)req,"%15s %4095s %31s",method,target,ver)!=3){free(req);text_response(c,400,"Bad Request","Bad Request");return;}
 int header_len=(int)(end-(char*)req)+4;char clbuf[64];DWORD total=header_value((char*)req,"Content-Length",clbuf,sizeof(clbuf))?(DWORD)strtoul(clbuf,NULL,10):0;
 unsigned char*body=NULL;if(total){body=(unsigned char*)malloc(total);if(!body){free(req);text_response(c,500,"Error","Out of memory");return;}DWORD have=(DWORD)(used-header_len);if(have>total)have=total;memcpy(body,req+header_len,have);while(have<total){k=recv(c,(char*)body+have,total-have,0);if(k<=0)break;have+=k;}if(have<total){free(body);free(req);text_response(c,400,"Bad Request","Incomplete request body");return;}}
 if(!strncmp(target,"/proxy",6)){proxy_request(c,method,(char*)req,body,total);free(body);free(req);return;}if(history_request(c,root,method,target,(char*)req,body,total)){free(body);free(req);return;}free(body);
 if(_stricmp(method,"GET")&&_stricmp(method,"HEAD")){free(req);text_response(c,405,"Method Not Allowed","Method Not Allowed");return;}char*q=strchr(target,'?');if(q)*q=0;if(!strcmp(target,"/"))strcpy(target,"/index.html");if(strstr(target,"..")||strchr(target,'\\')){free(req);text_response(c,403,"Forbidden","Forbidden");return;}for(char*p=target;*p;p++)if(*p=='/')*p='\\';char full[MAX_PATH*4];snprintf(full,sizeof(full),"%s%s",root,target);FILE*f=fopen(full,"rb");if(!f){free(req);text_response(c,404,"Not Found","Not Found");return;}_fseeki64(f,0,SEEK_END);__int64 sz=_ftelli64(f);_fseeki64(f,0,SEEK_SET);char h[1024];int hn=snprintf(h,sizeof(h),"HTTP/1.1 200 OK\r\nContent-Type: %s\r\nContent-Length: %lld\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n",mime(full),(long long)sz);send_all(c,h,hn);if(_stricmp(method,"HEAD")){char b[CHUNK];while((k=(int)fread(b,1,sizeof(b),f))>0)if(!send_all(c,b,k))break;}fclose(f);free(req);
}
static DWORD WINAPI client_worker(LPVOID arg){CLIENT_JOB*j=(CLIENT_JOB*)arg;handle(j->client,j->root);shutdown(j->client,SD_BOTH);closesocket(j->client);free(j);return 0;}

int main(void){SetConsoleOutputCP(CP_UTF8);char root[MAX_PATH*4];DWORD n=GetModuleFileNameA(NULL,root,sizeof(root));if(!n||n>=sizeof(root))return 1;char*s=strrchr(root,'\\');if(s)*s=0;WSADATA w;if(WSAStartup(MAKEWORD(2,2),&w))return 1;InitializeCriticalSection(&history_lock);SOCKET server=INVALID_SOCKET;int port;for(port=8765;port<=8785;port++){server=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);struct sockaddr_in a;memset(&a,0,sizeof(a));a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);a.sin_port=htons((u_short)port);if(server!=INVALID_SOCKET&&bind(server,(struct sockaddr*)&a,sizeof(a))==0&&listen(server,SOMAXCONN)==0)break;if(server!=INVALID_SOCKET)closesocket(server);server=INVALID_SOCKET;}if(server==INVALID_SOCKET){DeleteCriticalSection(&history_lock);MessageBoxA(NULL,"Ports 8765-8785 are unavailable.","GPT Image Tool",MB_ICONERROR);return 1;}char url[256];snprintf(url,sizeof(url),"http://127.0.0.1:%d/index.html",port);printf("GPT Image Tool PC Developer v1.0 started.\nParallel generation/edit proxy: enabled.\nURL: %s\nKeep this window open. Press Ctrl+C to stop.\n",url);ShellExecuteA(NULL,"open",url,NULL,root,SW_SHOWNORMAL);for(;;){SOCKET c=accept(server,NULL,NULL);if(c==INVALID_SOCKET)break;CLIENT_JOB*j=(CLIENT_JOB*)calloc(1,sizeof(CLIENT_JOB));if(!j){closesocket(c);continue;}j->client=c;strncpy(j->root,root,sizeof(j->root)-1);HANDLE th=CreateThread(NULL,0,client_worker,j,0,NULL);if(th)CloseHandle(th);else{closesocket(c);free(j);}}DeleteCriticalSection(&history_lock);return 0;}
